name: SonarCloud analysis

on:
  push:
  workflow_dispatch:
jobs:
  SAST :
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=${{ secrets.SONARCLOUD_PROJECTKEY }}
            -Dsonar.organization=${{ secrets.SONARCLOUD_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
          projectBaseDir: .
      - name: Validate Quality Gate
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_COMPLETE: ${{ github.repository_owner }}_${{ github.event.repository.name }}
        run: |
          echo "Validando el estado del Quality Gate... $SONAR_TOKEN , $REPO_NAME, $REPO_OWNER"
          analysisId=$(curl -s -u "$SONAR_TOKEN:" \
            "https://sonarcloud.io/api/ce/component?component=$REPO_COMPLETE" | jq -r '.current.analysisId')
          echo "analysisId: $analysisId."

          qualityGateStatus=$(curl -s -u "$SONAR_TOKEN:" \
            "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$analysisId" | jq -r '.projectStatus.status')

          if [ "$qualityGateStatus" != "OK" ]; then
            echo "El proyecto no cumple con el Quality Gate: $qualityGateStatus."
            echo "Verificando vulnerabilidades críticas..."
            vulnerabilities=$(curl -s -u "$SONAR_TOKEN:" \
              "https://sonarcloud.io/api/issues/search?componentKeys=$REPO_COMPLETE&types=VULNERABILITY&severities=CRITICAL,BLOCKER" | jq -r '.total')
            echo "total de vulnerabilidades encontradas: $vulnerabilities."
            if [ "$vulnerabilities" -gt 0 ]; then
              echo "Se encontraron $vulnerabilities vulnerabilidades críticas, bloqueantes. El proyecto no cumple con los estándares de seguridad."
              #exit 1
            fi
          else
            echo "Verificando existencia de vulnerabilidades medias..."
            vulnerabilitiesMajor=$(curl -s -u "$SONAR_TOKEN:" \
              "https://sonarcloud.io/api/issues/search?componentKeys=$REPO_COMPLETE&types=VULNERABILITY&severities=MAJOR" | tee response.json | jq -r '.total')
            respuesta=$(curl -s -u "$SONAR_TOKEN:" \
              "https://sonarcloud.io/api/issues/search?componentKeys=$REPO_COMPLETE&types=VULNERABILITY&severities=MAJOR")
            echo "respuesta servicio:"
            echo "$respuesta"
            echo "total de vulnerabilidades encontradas: $vulnerabilitiesMajor ."
            if [ "$vulnerabilitiesMajor" -gt 0 ]; then
              echo "Se encontraron $vulnerabilitiesMajor vulnerabilidades  medias. El proyecto no cumple con los estándares de seguridad."
              #exit 1
            fi
            echo "El proyecto cumple con el Quality Gate y no tiene vulnerabilidades críticas. Continuando sin problemas."
          fi
  SCA:
    needs: SAST
    runs-on: ubuntu-24.04
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@1.1.0
      env:
        JAVA_HOME: /opt/jdk
      id: Depcheck
      with:
        project: '${{ github.event.repository.name }}'
        path: '.'
        format: 'HTML'
        args: >
          --out ./reports
          --failOnCVSS 7
          --enableRetired
    - name: Parse results and set output variables
      id: parse-results
      run: |
        # Extract counts by severity using jq
        echo "leyendo carpeta $(ls .)"
        echo "leyendo carpeta reports$(ls ./reports)"
        CRITICAL=$(cat reports.json | jq -r '[.dependencies[].vulnerabilities[] | select(.severity == "CRITICAL")] | length')
        HIGH=$(cat reports.json | jq -r '[.dependencies[].vulnerabilities[] | select(.severity == "HIGH")] | length')
        MEDIUM=$(cat reports.json | jq -r '[.dependencies[].vulnerabilities[] | select(.severity == "MEDIUM")] | length')
        LOW=$(cat reports.json | jq -r '[.dependencies[].vulnerabilities[] | select(.severity == "LOW")] | length')
        
        echo "CRITICAL_COUNT=${CRITICAL}" >> $GITHUB_ENV
        echo "HIGH_COUNT=${HIGH}" >> $GITHUB_ENV
        echo "MEDIUM_COUNT=${MEDIUM}" >> $GITHUB_ENV
        echo "LOW_COUNT=${LOW}" >> $GITHUB_ENV
        
        # Fail if critical or high vulnerabilities exist
        if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
          echo "::error::Found ${CRITICAL} CRITICAL and ${HIGH} HIGH vulnerabilities!"
          exit 1
        fi
    - name: Upload Test Result
      uses: actions/upload-artifact@master
      with:
        name: Depcheck Report
        path: ./reports
