name: SonarCloud analysis

on:
  push:
  workflow_dispatch:
jobs:
  SAST :
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=${{ secrets.SONARCLOUD_PROJECTKEY }}
            -Dsonar.organization=${{ secrets.SONARCLOUD_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
          projectBaseDir: .
      - name: Validate Quality Gate
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_COMPLETE: ${{ github.repository_owner }}_${{ github.event.repository.name }}
        run: |
          echo "Validando el estado del Quality Gate... $SONAR_TOKEN , $REPO_NAME, $REPO_OWNER"
          analysisId=$(curl -s -u "$SONAR_TOKEN:" \
            "https://sonarcloud.io/api/ce/component?component=$REPO_COMPLETE" | jq -r '.current.analysisId')
          echo "analysisId: $analysisId."

          qualityGateStatus=$(curl -s -u "$SONAR_TOKEN:" \
            "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$analysisId" | jq -r '.projectStatus.status')

          if [ "$qualityGateStatus" != "OK" ]; then
            echo "El proyecto no cumple con el Quality Gate: $qualityGateStatus."
            echo "Verificando vulnerabilidades críticas..."
            vulnerabilities=$(curl -s -u "$SONAR_TOKEN:" \
              "https://sonarcloud.io/api/issues/search?componentKeys=$REPO_COMPLETE&types=VULNERABILITY&severities=CRITICAL,BLOCKER" | jq -r '.total')
            echo "total de vulnerabilidades encontradas: $vulnerabilities."
            if [ "$vulnerabilities" -gt 0 ]; then
              echo "Se encontraron $vulnerabilities vulnerabilidades críticas, bloqueantes. El proyecto no cumple con los estándares de seguridad."
              exit 1
            fi
          else
            echo "Verificando existencia de vulnerabilidades medias..."
            vulnerabilitiesMajor=$(curl -s -u "$SONAR_TOKEN:" \
              "https://sonarcloud.io/api/issues/search?componentKeys=$REPO_COMPLETE&types=VULNERABILITY&severities=MAJOR" | tee response.json | jq -r '.total')
            respuesta=$(curl -s -u "$SONAR_TOKEN:" \
              "https://sonarcloud.io/api/issues/search?componentKeys=$REPO_COMPLETE&types=VULNERABILITY&severities=MAJOR")
            echo "respuesta servicio:"
            echo "$respuesta"
            echo "total de vulnerabilidades encontradas: $vulnerabilitiesMajor ."
            if [ "$vulnerabilitiesMajor" -gt 0 ]; then
              echo "Se encontraron $vulnerabilitiesMajor vulnerabilidades  medias. El proyecto no cumple con los estándares de seguridad."
              exit 1
            fi
            echo "El proyecto cumple con el Quality Gate y no tiene vulnerabilidades críticas. Continuando sin problemas."
          fi
